services:
  vue-test:
    build: .
    image: vue-test
    container_name: vue-test
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3001"
    ports:
      - "3001:3001"
    networks:
      - apps
    restart: unless-stopped

networks:
  apps:
    external: true
